name: abbasjamali
favicon: null
layout_spectrum: 0.9815819230861962
typography_spectrum: 0.8296871385537088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4256198932416737
  lightness: 0.03793329233303666
  saturation: 0.7802806210238487
  rhythmicContrast: 0.3405121813993901
purpose: []
